### PR TITLE
i made it so the drill is now steam machine,,,, and it can now use electricity as well

### PR DESCRIPTION
**Pull request by kdcjxbsdnbgfdg**
however bc of someone goofing, or me....... it parallels 8x bc you cant actually change the parallel amount of a steaam multiblock.,,, also idk if steam multiblocks that dont parallel exist

### CODE REVIEW

**Comment by kdcjxbsdnbgfdg** [comment]
who thinks im merging this shit?

**Comment by kdcjxbsdnbgfdg** [comment]
you literally went one step forwards and one step backwards. Now we have to deal with it doing 8x parallel for no reason you doughtnut

**Comment by divine-ray** [comment]
i would like to comment that having parallels for oregen early on is rather handy

**Comment by kdcjxbsdnbgfdg** [comment]
fair enough but uhh i think it would be too strong or something

**Pull request merged**
